### PR TITLE
Fix Glottolog mapping; improve profile; regenerate CLDF

### PR DESCRIPTION
**Pull request by tresoldi**
This PR:

  - Fixes Glottolog mapping by correcting mappings, replacing bookkeeping codes, splitting different languages that were mapped to the same glottocode (many thanks to @MacyL for her help in fixing the Hmong languages that were mapped to the same code!)
  - Fixes the orthographic profile, with some improvements and now achieving 100% coverage

### CODE REVIEW

**Comment by tresoldi** [comment]
Pinging @XachaB

**Comment by XachaB** [comment]
Thanks ! So fast I didn't even have time to write an issue :)

**Review by LinguList — APPROVED** [review]

**Review by xrotwang — APPROVED** [review]
Looks good. Does the language mapping have to be reviewed by someone else?

**Comment by tresoldi** [comment]
The language mapping would benefit from revisions, including less conservative ones (I only touched those that were problematic), no doubt about that.

Nonetheless, considering that this mapping improves the one currently in `master`, I suppose I can merge it?

**Comment by xrotwang** [comment]
@tresoldi ok, go ahead and merge.

**Pull request merged**
